#!/usr/bin/env bash

## date:   2022-03-08
## author: duruao@gmail.com
## desc:   login container with the administrator

set -e

COMMAND=("$@")

## build user
if [ -n "${BUILD_USER}" ] && [ -n "${BUILD_UID}" ] && [ -n "${BUILD_GROUP}" ] && [ -n "${BUILD_GID}" ] && [ -n "${BUILD_HOME}" ]; then
  useradd -ms /bin/bash -d "${BUILD_HOME}" "${BUILD_USER}"
  usermod -aG sudo "${BUILD_USER}"
  echo "${BUILD_USER}":"${BUILD_USER}" | chpasswd
  usermod -u "${BUILD_UID}" "${BUILD_USER}" 1>/dev/null 2>&1
  groupmod -g "${BUILD_GID}" "${BUILD_GROUP}" 1>/dev/null 2>&1

  cp -rf /duck/.vim "${BUILD_HOME}"/.vim
  cp -f /duck/.vimrc "${BUILD_HOME}"/.vimrc
  cp -f /duck/.tmux.conf "${BUILD_HOME}"/.tmux.conf
  cat /duck/user.PS1 >>"${BUILD_HOME}"/.bashrc

  chown -R "${BUILD_USER}":"${BUILD_USER}" "${BUILD_HOME}"
fi

${COMMAND[@]+"${COMMAND[@]}"}
