#!/usr/bin/env bash

##  Copyright (c) 2022, DURUYAO. All rights reserved.
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.

## date:   2022-03-08
## author: duruao@gmail.com
## desc:   login container with the same user of host

set -e

COMMAND=("$@")

## build user
if [ -n "${BUILD_USER}" ] && [ -n "${BUILD_UID}" ] && [ -n "${BUILD_GROUP}" ] && [ -n "${BUILD_GID}" ] && [ -n "${BUILD_HOME}" ]; then
  useradd -ms /bin/bash -d "${BUILD_HOME}" "${BUILD_USER}"
  usermod -aG sudo "${BUILD_USER}"
  echo "${BUILD_USER}":"${BUILD_USER}" | chpasswd
  usermod -u "${BUILD_UID}" "${BUILD_USER}" 1>/dev/null 2>&1
  groupmod -g "${BUILD_GID}" "${BUILD_GROUP}" 1>/dev/null 2>&1

  cp -rf /duck/.vim "${BUILD_HOME}"/.vim
  cp -f /duck/.vimrc "${BUILD_HOME}"/.vimrc
  cp -f /duck/.tmux.conf "${BUILD_HOME}"/.tmux.conf
  cat /duck/user.bashrc >>"${BUILD_HOME}"/.bashrc

  chown -R "${BUILD_USER}":"${BUILD_USER}" "${BUILD_HOME}"
fi

nohup /usr/sbin/sshd -D 1>>/tmp/nohup.out 2>&1 &
sudo -u "#${BUILD_UID}" --preserve-env HOME="${BUILD_HOME}" "${COMMAND[@]}"
