#!/usr/bin/env bash

## date:   2022-01-21
## author: duruao@gmail.com
## desc:

set -euo pipefail

function errorln() {
  printf "\033[1;32;31m%s\n\033[m" "${1}"
}

function show_usage() {
  cat <<EOF
Usage: dk attach [OPTIONS] IMAGE

Attach to a running dock-duck container

Options:
      --dry-run                 Print the docker command to be run, but do not execute it
  -h, --help                    Display this help message

See more about DockDucK at https://github.com/duruyao/DockDucK

EOF
}

dk_home="$(dirname "$(dirname "$(realpath "$0")")")"
dk_data_home="${dk_home}/dk-data"
dk_containers_file="${dk_data_home}"/containers.txt
