#!/usr/bin/env bash

## date:   2022-01-21
## author: duruao@gmail.com
## desc:

set -euo pipefail

function errorln() {
  printf "\033[1;32;31m%s\n\033[m" "${1}"
}

function show_usage() {
  cat <<EOF
Usage: dk detach [OPTIONS] IMAGE

Run a command in a new dock-duck container

Options:
      --dry-run                 Print the docker command to be run, but do not execute it
  -h, --help                    Display this help message
      --name STRING             Assign name to the container (default: "$USER.IMAGE.TAG")
      --other-flags LIST        Append other flags to the command 'docker run ...'
  -p, --publish LIST            Publish a container's port(s) to the host (default: ALL_EXPOSED_PORTS:RANDOM_PORTS)
  -v, --volume LIST             Bind mount a volume (default: "$PWD:$PWD")

See more about DockDucK at https://github.com/duruyao/DockDucK

EOF
}

dk_home="$(dirname "$(dirname "$(realpath "$0")")")"
dk_data_home="${dk_home}/dk-data"
dk_containers_file="${dk_data_home}"/containers.txt
