#!/usr/bin/env bash

## date:   2022-01-21
## author: duruao@gmail.com
## desc:   list running dock-duck containers

set -euo pipefail

function errorln() {
  printf "\033[1;32;31m%s\n\033[m" "${1}"
}

function show_usage() {
  cat <<EOF
Usage: dk ps [OPTIONS]

List running dock-duck containers

Options:
  -h, --help                    Display this help message

See more about DockDucK at https://github.com/duruyao/DockDucK

EOF
}

dk_home="$(dirname "$(dirname "$(realpath "$0")")")"
dk_data_home="${dk_home}/dk-data"
dk_containers_file="${dk_data_home}"/containers.txt

## parse arguments
while (($#)); do
  case "$1" in
  -h | --help)
    show_usage
    exit 0
    ;;

  --* | -* | *)
    errorln "Error: Unknown flag: $1" >&2
    show_usage >&2
    exit 1
    ;;
  esac
done

docker ps -a | grep NAMES

grep -v '^ *#' <"${dk_containers_file}" | while IFS= read -r container; do
  if [ -n "${container}" ]; then
    docker ps -a | grep "${container}"
  fi
done
