#!/usr/bin/env bash

##  Copyright (c) 2022, DURUYAO. All rights reserved.
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.

## date:   2022-01-20
## author: duruao@gmail.com
## desc:   uninstall dock-duck from $DK_HOME

set -euo pipefail

function error_ln() {
  printf "\033[1;32;31m%s\n\033[m" "$1"
}

function warning_ln() {
  printf "\033[1;33m%s\n\033[m" "$1"
}

function info_ln() {
  printf "\033[0;32;32m%s\n\033[m" "$1"
}

function show_usage() {
  cat <<EOF
Usage: dk uninstall [OPTIONS]

Uninstall dock-duck from \$DK_HOME

Options:
  -h, --help                    Display this help message

See more about DockDuck at https://github.com/duruyao/DockDuck

EOF
}

## parse arguments
while (($#)); do
  case "$1" in
  -h | --help)
    show_usage
    exit 0
    ;;

  --* | -* | *)
    error_ln "Error: Unknown flag: '$1'" >&2
    show_usage >&2
    exit 1
    ;;
  esac
done

echo "Uninstalling ..."
echo

if [ "NOTFOUND" == "${DK_HOME-NOTFOUND}" ]; then
  warning_ln "Warning: \$DK_HOME not found"
  exit
fi

# shellcheck disable=SC2153
dk_home="${DK_HOME}"
dk_app_home="${dk_home}"/app
dk_img_home="${dk_home}"/img
dk_tools_home="${dk_home}"/tools

rm -rf "${dk_app_home}"
rm -rf "${dk_img_home}"
rm -rf "${dk_tools_home}"

sed -i "/DockDuck Bash Config/d" "${HOME}"/.bashrc

echo "Uninstall dock-duck from ${dk_home}"
echo ""
echo "Try 'source ~/.bashrc' to reload PATH"
